// This file is auto-generated by scripts/upload-backgrounds.ts
// DO NOT EDIT MANUALLY

export const backgroundImageMapping: Record<string, string> = {
  "/backgrounds/asset-1.jpg": "backgrounds/asset-1",
  "/backgrounds/asset-10.jpg": "backgrounds/asset-10",
  "/backgrounds/asset-11.jpg": "backgrounds/asset-11",
  "/backgrounds/asset-2.jpg": "backgrounds/asset-2",
  "/backgrounds/asset-3.jpg": "backgrounds/asset-3",
  "/backgrounds/asset-4.jpg": "backgrounds/asset-4",
  "/backgrounds/asset-5.jpg": "backgrounds/asset-5",
  "/backgrounds/asset-6.jpg": "backgrounds/asset-6",
  "/backgrounds/asset-7.jpg": "backgrounds/asset-7",
  "/backgrounds/asset-8.jpg": "backgrounds/asset-8",
  "/backgrounds/asset-9.jpg": "backgrounds/asset-9",
  "/backgrounds/mac-assest-2.jpg": "backgrounds/mac-assest-2",
  "/backgrounds/mac-asset-1.jpeg": "backgrounds/mac-asset-1",
  "/backgrounds/mac-asset-10.jpg": "backgrounds/mac-asset-10",
  "/backgrounds/mac-asset-3.jpg": "backgrounds/mac-asset-3",
  "/backgrounds/mac-asset-4.jpg": "backgrounds/mac-asset-4",
  "/backgrounds/mac-asset-5.jpg": "backgrounds/mac-asset-5",
  "/backgrounds/mac-asset-6.jpeg": "backgrounds/mac-asset-6",
  "/backgrounds/mac-asset-7.png": "backgrounds/mac-asset-7",
  "/backgrounds/mac-asset-8.jpg": "backgrounds/mac-asset-8",
  "/backgrounds/mac-asset-9.jpg": "backgrounds/mac-asset-9"
};

export const cloudinaryPublicIds: string[] = [
  "backgrounds/asset-1",
  "backgrounds/asset-10",
  "backgrounds/asset-11",
  "backgrounds/asset-2",
  "backgrounds/asset-3",
  "backgrounds/asset-4",
  "backgrounds/asset-5",
  "backgrounds/asset-6",
  "backgrounds/asset-7",
  "backgrounds/asset-8",
  "backgrounds/asset-9",
  "backgrounds/mac-assest-2",
  "backgrounds/mac-asset-1",
  "backgrounds/mac-asset-10",
  "backgrounds/mac-asset-3",
  "backgrounds/mac-asset-4",
  "backgrounds/mac-asset-5",
  "backgrounds/mac-asset-6",
  "backgrounds/mac-asset-7",
  "backgrounds/mac-asset-8",
  "backgrounds/mac-asset-9",
];

// Public ID for sign-in page background
export const SIGN_IN_BACKGROUND_PUBLIC_ID = 'backgrounds/mac-asset-7';

// Public ID for sign-up page background
export const SIGN_UP_BACKGROUND_PUBLIC_ID = 'backgrounds/mac-asset-7';
